### ISSUE TITLE
Question: What is analytic.resource.plan.line and account.analytic.line.plan

### ISSUE THREAD

**Issue by kittiu** [kittiu/aagc#9]
I see these objects many place, still not capture what it is,
How is it related to account.analytic.line?

**Comment by AaronHForgeFlow** [comment]
Sorry, I posted this while I was editing. I am updating this.

**Comment by AaronHForgeFlow** [comment]
@kittiu Please see the explanation form the readme of the analytic_plan modules. It will help you to understand:
https://github.com/ForgeFlow/eficent-odoo-addons/blob/12.0/analytic_plan/README.rst
https://github.com/ForgeFlow/eficent-odoo-addons/blob/12.0/analytic_resource_plan/README.rst

As a summary:
  - They are not related to account analytic lines.
  - Analytic plan lines will just capture **planned** costs and revenues for the project. But they will not impact accounting. They are useful to check if we are doing according to the plan or not.
  - Analytic resource plan lines will capture **planned** **resources** for the project. In your use case, this is planned material for the project. Confirming a planned resource for a specific date, will generate demand  for the project. MRP multi level module from OCA will capture this demand and propose Purchases and Manufacturing orders in order to have those resources available to be used for the project at the required date.

Hope this helps you to understand a bit.

Regards.

**Comment by kittiu** [comment]
@AaronHForgeFlow , Is this correct?
- Planned Cost and Revenue comes from Project Bids
- Planned Resource comes from what we create in project's Resources
- And to trigger PO and MO is only from this project's Resources, correct?

**Comment by AaronHForgeFlow** [comment]
> @AaronHForgeFlow , Is this correct?
> 
> * Planned Cost and Revenue comes from Project Bids

You can create them form the bids, or by hand, normally you only use one source of planned costs. 

Ps: confirming resource plan lines will also generate analytic.plan.line, but those will go to a different planned version, so they are not mixed with the created ones from other sources.

> * Planned Resource comes from what we create in project's Resources

Yes, normally it is used just for planning material resources.

> * And to trigger PO and MO is only from this project's Resources, correct?

Yes, only from resources. Actually, they will create just "demand" like sales order do. They do not create PO and MO directly. The project manager have to go every day to the MRP application and see what it is needed.

**Comment by kittiu** [comment]
Great! a lot more cleared now. Thanks!

**Comment by AaronHForgeFlow** [comment]
Thank you! I'm glad to help.
